# Generated by assistant
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar_url',
            field=models.CharField(max_length=255, null=True, blank=True),
        ),
    ]
