# Generated by Django 5.0 on 2026-05-14 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='onboarding_submitted',
            field=models.BooleanField(default=False),
        ),
    ]
