# Generated by Django 5.0 on 2026-05-14 03:41

from django.db import migrations


def approve_existing_users(apps, schema_editor):
    """Approve all existing users to preserve access for legacy members."""
    User = apps.get_model('accounts', 'User')
    User.objects.all().update(is_approved=True)


def reverse_approve(apps, schema_editor):
    """Reverse: unapprove all users (for rollback)."""
    User = apps.get_model('accounts', 'User')
    User.objects.all().update(is_approved=False)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_onboarding_submitted'),
    ]

    operations = [
        migrations.RunPython(approve_existing_users, reverse_approve),
    ]
