services:
  - type: web
    name: community-union-backend
    env: docker
    plan: free
    repo: https://github.com/WorldOfDiversities/community_union_project-backend
    dockerfilePath: Dockerfile
    startCommand: gunicorn config.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DJANGO_SECRET_KEY
        fromDatabase: false
      - key: DATABASE_URL
        fromDatabase: false
      - key: DEBUG
        value: "false"
      - key: CORS_ALLOWED_ORIGINS
        fromDatabase: false
        value: https://community-union-project.vercel.app
      - key: ALLOWED_HOSTS
        fromDatabase: false
    disk: 0
