# Generated by Django 6.0.5 on 2026-05-10 17:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DuesPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('billing_period', models.CharField(max_length=50)),
                ('due_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('method', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Current', 'Current'), ('Paid', 'Paid'), ('Overdue', 'Overdue')], max_length=20)),
                ('paid_on', models.DateField(blank=True, null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dues_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dues Payment',
                'verbose_name_plural': 'Dues Payments',
                'db_table': 'dues_payment',
                'ordering': ['-due_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MemberStanding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active_since_years', models.PositiveIntegerField(default=0)),
                ('payment_rate', models.PositiveIntegerField(default=0)),
                ('status_label', models.CharField(max_length=50)),
                ('current_balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='standing', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Member Standing',
                'verbose_name_plural': 'Member Standings',
                'db_table': 'dues_member_standing',
            },
        ),
    ]
