# Generated by Django 6.0.5 on 2026-05-11 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('union_name', models.CharField(default='Community Union Africa', max_length=255)),
                ('chapter_number', models.CharField(default='0104', max_length=50)),
                ('primary_contact_email', models.EmailField(default='admin@communityunion.africa', max_length=254)),
                ('time_zone', models.CharField(default='Eastern Standard Time (EST)', max_length=100)),
                ('physical_address', models.TextField(default='324 Madaraka Ave, Accra, Ghana')),
                ('chapter_details', models.TextField(default='Wungu Regional Office | EST: 5:00 PM')),
                ('logo_url', models.URLField(blank=True, null=True)),
                ('dues_sms_enabled', models.BooleanField(default=False)),
                ('dues_email_enabled', models.BooleanField(default=True)),
                ('meeting_sms_enabled', models.BooleanField(default=False)),
                ('meeting_email_enabled', models.BooleanField(default=True)),
                ('member_updates_sms_enabled', models.BooleanField(default=False)),
                ('member_updates_email_enabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Organization Settings',
                'verbose_name_plural': 'Organization Settings',
            },
        ),
    ]
