# Generated by Django 6.0.5 on 2026-05-11 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationsettings',
            name='logo_url',
        ),
        migrations.AddField(
            model_name='organizationsettings',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='logos/'),
        ),
    ]
