# Generated by Django 6.0.5 on 2026-05-11 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meeting_id', models.CharField(max_length=20, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('scheduled', 'Scheduled'), ('social_gathering', 'Social Gathering'), ('unlisted', 'Unlisted')], default='scheduled', max_length=30)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='upcoming', max_length=20)),
                ('scheduled_at', models.DateTimeField()),
                ('location', models.CharField(max_length=255)),
                ('attendees', models.PositiveIntegerField(default=0)),
                ('action_items', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('has_image', models.BooleanField(default=False)),
                ('image_url', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'verbose_name': 'Meeting',
                'verbose_name_plural': 'Meetings',
                'db_table': 'meetings_meeting',
                'ordering': ['scheduled_at', '-created_at'],
            },
        ),
    ]
