# Generated by Django 6.0.5 on 2026-05-10 17:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity_id', models.CharField(max_length=20, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('training', 'Training'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], max_length=20)),
                ('scheduled_at', models.DateTimeField()),
                ('location', models.CharField(max_length=255)),
                ('organizer', models.CharField(max_length=255)),
                ('attendees', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Activity',
                'verbose_name_plural': 'Activities',
                'db_table': 'activities_activity',
                'ordering': ['scheduled_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ActivityAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('Attended', 'Attended'), ('Missed', 'Missed')], max_length=20)),
                ('attended_on', models.DateField(blank=True, null=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='activities.activity')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_attendance', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activity Attendance',
                'verbose_name_plural': 'Activity Attendance',
                'db_table': 'activities_attendance',
                'ordering': ['-attended_on', '-created_at'],
            },
        ),
    ]
