# Generated by Django 5.0 on 2026-05-18 03:28

import apps.notifications.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='expires_at',
            field=models.DateTimeField(default=apps.notifications.models.default_announcement_expiry),
        ),
    ]
